### ISSUE TITLE
Incompatible with Reset Custom Study Limit addon

### ISSUE THREAD

**Issue by akavi1** [Yutsuten/anki-lifedrain#129]
Having both addons results in the following error after clicking on a deck.
https://ankiweb.net/shared/info/738867649
https://github.com/telotortium/anki-reset-limits
 

Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-06-08 23:41:51
Add-ons possibly involved: ⁨Life Drain, Reset Custom Study Limit Increases⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/taskman.py", line 101, in _on_closures_pending
  File "aqt/taskman.py", line 71, in <lambda>
  File "aqt/taskman.py", line 90, in wrapped_done
  File "aqt/operations/__init__.py", line 112, in wrapped_done
  File "aqt/deckbrowser.py", line 123, in <lambda>
  File "aqt/main.py", line 1126, in onOverview
  File "aqt/main.py", line 672, in moveToState
  File "aqt/main.py", line 691, in _overviewState
  File "aqt/overview.py", line 60, in show
  File "aqt/overview.py", line 66, in refresh
  File "decorator.py", line 232, in fun
  File "anki/hooks.py", line 89, in decorator_wrapper
  File "anki/hooks.py", line 81, in repl
  File "/Users/name/Library/Application Support/Anki2/addons21/738867649/ResetLimits.py", line 85, in _renderBottom
    self.bottom.draw(buf)
  File "/Users/name/Library/Application Support/Anki2/addons21/715575551/main.py", line 84, in bottom_bar_draw
    if isinstance(kwargs['web_context'], OverviewBottomBar):
KeyError: 'web_context'

**Comment by Yutsuten** [comment]
Seems that that add-on also adds some buttons to the Deck Overview screen.
I don't understand why two add-ons doing this would throw a `KeyError` though...

I'll have to change that code anyway in #126 as it is incompatible with Anki 2.1.50, so likely will be fixed the next release.

Thank you for reporting. :+1:

**Comment by Yutsuten** [comment]
Looks like Reset Custom Study Limit is overriding `Overview._renderBottom` and calling [`draw` without the `web_context`](https://github.com/telotortium/anki-reset-limits/blob/4cef97d1fa2b3152bcd9ff359878d88a44ca67b6/ResetLimits.py#L85) parameter [Anki uses by default](https://github.com/ankitects/anki/blob/3969487e772eef60730176344d4d50334c616710/qt/aqt/overview.py#L297-L299), effectively breaking my code.

Sorry but I won't fix this, who did the dirty stuff is the another add-on.

**Comment by Yutsuten** [comment]
I created an issue in the Reset Custom Study Limit Increases repository. Lets hope the author fixes it.
