### ISSUE TITLE
Anki won't start with addon enabled

### ISSUE THREAD

**Issue by akavi1** [Yutsuten/anki-lifedrain#146]
I enabled the addon and it worked fine until I quit the Anki app. Now when I try to open Anki, I get this error. The profile selection page does not appear. I opened Anki in recovery mode and disabled the addon, and I was then able to open Anki normally.

Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Mac 12.4
Flags: frz=True ao=True sv=?
Add-ons, last update check: 2022-08-29 18:28:34
Add-ons possibly involved: ⁨Life Drain⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.progress", line 118, in handler
  File "aqt.main", line 197, in on_window_init
  File "aqt.main", line 288, in setupProfile
  File "aqt.main", line 294, in showProfileManager
  File "aqt.main", line 672, in moveToState
  File "aqt.hooks_gen", line 3945, in __call__
  File "/Users/name/Library/Application Support/Anki2/addons21/715575551/main.py", line 52, in <lambda>
    lambda *args: lifedrain.screen_change(args[0]))
  File "/Users/name/Library/Application Support/Anki2/addons21/715575551/lifedrain.py", line 172, in screen_change
    self.deck_manager.update()
  File "/Users/name/Library/Application Support/Anki2/addons21/715575551/deck_manager.py", line 45, in update
    deck_id = self._get_deck_id()
  File "/Users/name/Library/Application Support/Anki2/addons21/715575551/deck_manager.py", line 159, in _get_deck_id
    conf = self._deck_conf.get()
  File "/Users/name/Library/Application Support/Anki2/addons21/715575551/database.py", line 58, in get
    deck = self._main_window.col.decks.current()
AttributeError: 'NoneType' object has no attribute 'decks'

**Comment by Yutsuten** [comment]
Thanks for the bug report. This is a regression from the last release I did, and seems to only happen if you have more than one profile. I'll upload a fix for this within a few minutes.
Sorry for the trouble.

**Comment by Yutsuten** [comment]
I pushed a new release with the fix. Could you see if it is now working from your side?

**Comment by akavi1** [comment]
It works now. Thank you!
