### ISSUE TITLE
Lifedrain Addon Reoccurring Crash

### ISSUE THREAD

**Issue by KerbalJeb1** [Yutsuten/anki-lifedrain#171]
**Anki version & Operating System:** 
Windows 11,  ⁨2.1.65 

**When does the crash happens?** 
after failing a card

**Traceback:** 

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 5.15.2 PyQt 5.15.5
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-11-07 00:12:05

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 122, in _on_closures_pending
  File "aqt.taskman", line 71, in <lambda>
  File "aqt.taskman", line 90, in wrapped_done
  File "aqt.operations", line 125, in wrapped_done
  File "aqt.deckbrowser", line 129, in <lambda>
  File "aqt.main", line 1224, in onOverview
  File "aqt.main", line 711, in moveToState
  File "_aqt.hooks", line 4757, in __call__
  File "C:\Users\xavie\AppData\Roaming\Anki2\addons21\715575551\main.py", line 50, in <lambda>
    gui_hooks.state_will_change.append(lambda *args: lifedrain.screen_change(args[0]))
  File "C:\Users\xavie\AppData\Roaming\Anki2\addons21\715575551\lifedrain.py", line 136, in screen_change
    self.deck_manager.answer(
  File "C:\Users\xavie\AppData\Roaming\Anki2\addons21\715575551\decorators.py", line 25, in _wrapper
    return func(self, self._bar_info[self._cur_deck_id], *args, **kwargs)
  File "C:\Users\xavie\AppData\Roaming\Anki2\addons21\715575551\deck_manager.py", line 157, in answer
    self.damage(card_type=card_type)
  File "C:\Users\xavie\AppData\Roaming\Anki2\addons21\715575551\decorators.py", line 25, in _wrapper
    return func(self, self._bar_info[self._cur_deck_id], *args, **kwargs)
  File "C:\Users\xavie\AppData\Roaming\Anki2\addons21\715575551\deck_manager.py", line 144, in damage
    self._update_life(bar_info, -1 * damage)
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'

**Comment by Yutsuten** [comment]
Thank you for reporting. I'm investigating the issue and will upload a fix soon.

**Comment by Yutsuten** [comment]
I have fixed the issue. Please update the add-on, open the Lifedrain's Deck Settings window and save once again to fix some damage values in the database. Do it for every deck you see the error.

I'm very sorry for the issue. Hopefully now the bug is gone. If you find any other issues, please fell free to report here.
