### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by YourUberdriver** [Yutsuten/anki-lifedrain#183]
Hi,

unfortunately when changing to any bar style other than default leads to an error.

Here is the message i get:
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-15.1-arm64-arm-64bit

Traceback (most recent call last):
  File "aqt.addons", line 1024, in onConfig
  File "/Users/richardbuch/Library/Application Support/Anki2/addons21/715575551/lifedrain.py", line 65, in global_settings
    self.deck_manager.update(self.status['screen'])
  File "/Users/richardbuch/Library/Application Support/Anki2/addons21/715575551/deck_manager.py", line 59, in update
    self._update_progress_bar_style()
  File "/Users/richardbuch/Library/Application Support/Anki2/addons21/715575551/deck_manager.py", line 277, in _update_progress_bar_style
    self._progress_bar.set_style(progress_bar_style)
  File "/Users/richardbuch/Library/Application Support/Anki2/addons21/715575551/progress_bar.py", line 102, in set_style
    self._update_bar_color()
  File "/Users/richardbuch/Library/Application Support/Anki2/addons21/715575551/progress_bar.py", line 196, in _update_bar_color
    palette.setColor(self._qt.QPalette.Highlight, fg_color)
AttributeError: type object 'QPalette' has no attribute 'Highlight'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Audiovisual Feedback ['231569866', 2023-07-09T05:34, '0.8', mod]
Life Drain ['715575551', 2024-04-30T09:15, 'None', mod]

===IDs of active AnkiWeb add-ons===
231569866 715575551

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Speed Focus Mode auto-alert auto-reveal auto-answer ['1046608507', 2022-12-16T12:24, 'None', '']

**Comment by Yutsuten** [comment]
Thank you for the bug report!

I wonder when it started to fail because the last time I tested it was working... But now it is indeed throwing an error. I'm looking for a fix now.

**Comment by Yutsuten** [comment]
OK I fixed it here https://github.com/Yutsuten/anki-lifedrain/commit/2655ceec9833a6ce0f68ea471ad4fac2b36c3755

I'll test locally for a while and eventually I'll make a new release with this patch!
I also made a change to only allow choosing styles that actually work.

Thank you for the report again!

**Comment by YourUberdriver** [comment]
:)
