### ISSUE TITLE
Incompatibility with anki-2.1.21beta1

### ISSUE THREAD

**Issue by Cupbox** [Yutsuten/anki-lifedrain#48]
Debug info:
Anki 2.1.21 (683b7983) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-02-19 10:11:29

Caught exception:
Traceback (most recent call last):
  File "aqt\progress.py", line 76, in handler
  File "C:\Users\John Smith\AppData\Roaming\Anki2\addons21\715575551\lifedrain.py", line 584, in timerTrigger
    lifeDrain.deckBarManager.recover(False, 0.1)
  File "C:\Users\John Smith\AppData\Roaming\Anki2\addons21\715575551\lifedrain.py", line 548, in recover
    runHook('LifeDrain.gameOver')
  File "lib\site-packages\anki\hooks.py", line 555, in runHook
  File "C:\Users\John Smith\AppData\Roaming\Anki2\addons21\PomodoroTimer\lifedrain_pomodoroTimer.py", line 123, in pomodoroTimer
    mw.web.stdHtml(TOMATO_ASCII%(msg,time),
  File "aqt\webview.py", line 333, in stdHtml
TypeError: can only concatenate list (not "str") to list

**Comment by Yutsuten** [comment]
Hello @Cupbox , thank you for reporting this bug!

---

By checking your traceback, I think the problem is not on LifeDrain itself but on an addon based on Lifedrain, named PomodoroTimer.

The problem raised when the `LifeDrain.gameOver` hook ran.

```
File "C:\Users\John Smith\AppData\Roaming\Anki2\addons21\715575551\lifedrain.py", line 548, in recover
runHook('LifeDrain.gameOver')
```

The execution then jumped to `addons21\PomodoroTimer\lifedrain_pomodoroTimer.py` (this addon does not seem the be installed from the AnkiWeb, are you the developer of this?) and failed at line 123 of `lifedrain_pomodoroTimer.py`.

```
mw.web.stdHtml(TOMATO_ASCII%(msg,time)
```

---

So if you are the developer of that addon, use this part of the traceback to fix it.

```
File "C:\Users\John Smith\AppData\Roaming\Anki2\addons21\PomodoroTimer\lifedrain_pomodoroTimer.py", line 123, in pomodoroTimer
mw.web.stdHtml(TOMATO_ASCII%(msg,time),
File "aqt\webview.py", line 333, in stdHtml
TypeError: can only concatenate list (not "str") to list
```

**Comment by Cupbox** [comment]
Thank you for the information. I'll open an issue informing him about it.
