### ISSUE TITLE
Update 6/3/20 issue

### ISSUE THREAD

**Issue by Schqwamboni** [Yutsuten/anki-lifedrain#79]
The update today has resulted in an error message when opening Anki and the only way to fix it is to disable the Life Drain add on. My current version of Anki is 2.1.21. Here is the error message presented to me:

**First Dialogue box:** 

![image](https://user-images.githubusercontent.com/48225533/83657357-fb125880-a57d-11ea-9ac4-725422e3fe1a.png)

Anki was unable to open your collection file. If problems persist after restarting your computer, please use the Open Backup button in the profile manager.

Debug info:
Traceback (most recent call last):
  File "aqt\main.py", line 433, in loadCollection
  File "aqt\main.py", line 468, in _loadCollection
  File "aqt\main.py", line 589, in moveToState
  File "aqt\main.py", line 596, in _deckBrowserState
  File "aqt\deckbrowser.py", line 38, in show
  File "aqt\deckbrowser.py", line 100, in _renderPage
  File "aqt\deckbrowser.py", line 114, in __renderPage
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-40>", line 2, in _drawButtons
  File "lib\site-packages\anki\hooks.py", line 530, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 525, in repl
  File "aqt\deckbrowser.py", line 343, in _drawButtons
  File "C:\Users\HT\AppData\Roaming\Anki2\addons21\715575551\main.py", line 93, in bottom_bar_draw
    if isinstance(kwargs['web_context'], OverviewBottomBar):
KeyError: 'web_context'

**And the following dialogue box:**

Debug info:
Anki 2.1.21 (f1734a47) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=?
Add-ons, last update check: 2020-06-03 09:26:14

Caught exception:
Traceback (most recent call last):
  File "aqt\progress.py", line 73, in handler
  File "aqt\main.py", line 155, in setupProfileAfterWebviewsLoaded
  File "aqt\main.py", line 192, in setupProfile
  File "aqt\main.py", line 342, in loadProfile
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-136>", line 2, in loadCollection
  File "lib\site-packages\anki\hooks.py", line 530, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 521, in repl
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-134>", line 2, in loadCollection
  File "lib\site-packages\anki\hooks.py", line 530, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 521, in repl
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-132>", line 2, in loadCollection
  File "lib\site-packages\anki\hooks.py", line 530, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 522, in repl
  File "C:\Users\HT\AppData\Roaming\Anki2\addons21\874215009\advancedbrowser\basic_fields.py", line 75, in myLoadCollection
    mw.col.db._db.create_function("nameForDeck", 1, self.nameForDeck)
AttributeError: 'NoneType' object has no attribute 'db'

**Comment by Yutsuten** [comment]
Thank you for reporting the issue!

I was looking into the source code of Anki 2.1.21, and seems that it is incompatible with a new feature I have just added.

I'll create a new release branch that will rollback people using Anki versions <= 2.1.21 to the previous version of Life Drain.

**Comment by Yutsuten** [comment]
I just added the new release branch. Can you check later if the issue is solved for you and report here?

**Comment by Yutsuten** [comment]
I was testing here and seems that you'll need to remove the Life Drain add-on and re-add to fix it.

**Comment by Schqwamboni** [comment]
Thank you for your prompt work to update the add-on again! The newest update that you pushed through was detected by anki and upon installation has fixed my issue. I did not have to remove Life Drain then re-add it. It worked with just the update. Thanks again!
